[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*.spz"   # or more broadly: "/**/*.spz"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/octet-stream"
